# registry.py (SAFE placeholder registry)

PAYLOAD_REGISTRY = {

    # ---------------- XSS PLACEHOLDERS ----------------
    "XSS_REFLECTED_001": "<REFLECTED_TEST_STRING_1>",
    "XSS_IMG_ONERROR_002": "<IMG_ONERROR_TEST_1>",
    "XSS_SVG_003": "<SVG_TEST_1>",
    "XSS_IFRAME_004": "<IFRAME_TEST_1>",
    "XSS_EVENT_005": "<EVENT_HANDLER_TEST_1>",
    "XSS_INPUT_006": "<INPUT_TEST_1>",
    "XSS_META_007": "<META_TEST_1>",
    "XSS_ONLOAD_008": "<ONLOAD_TEST_1>",
    "XSS_STYLE_009": "<STYLE_TEST_1>",
    "XSS_IMG_SRC_010": "<IMG_SRC_TEST_1>",
    "XSS_LINK_011": "<LINK_TEST_1>",
    "XSS_ONMOUSE_012": "<ONMOUSE_TEST_1>",
    "XSS_SCRIPT_SRC_013": "<SCRIPT_SRC_TEST_1>",
    "XSS_TEMPLATE_014": "<TEMPLATE_TEST_1>",
    "XSS_CUSTOM_015": "<CUSTOM_XSS_TEST_1>",

    # ---------------- SQLi PLACEHOLDERS ----------------
    "SQLI_UNION_001": "<UNION_TEST_1>",
    "SQLI_BOOLEAN_002": "<BOOLEAN_TEST_1>",
    "SQLI_TIME_003": "<TIME_BASED_TEST_1>",
    "SQLI_ERROR_004": "<ERROR_BASED_TEST_1>",
    "SQLI_STACKED_005": "<STACKED_TEST_1>",
    "SQLI_BLIND_006": "<BLIND_TEST_1>",
    "SQLI_UNION_SELECT_007": "<UNION_SELECT_TEST_1>",
    "SQLI_COMMENT_TRUNC_008": "<COMMENT_TRUNC_TEST_1>",
    "SQLI_CLEANSING_009": "<CLEANSING_TEST_1>",
    "SQLI_AUTHBYPASS_010": "<AUTHBYPASS_TEST_1>",
    "SQLI_CONCAT_011": "<CONCAT_TEST_1>",
    "SQLI_HEX_012": "<HEX_TEST_1>",
    "SQLI_CAST_013": "<CAST_TEST_1>",
    "SQLI_SLEEP_014": "<SLEEP_TEST_1>",
    "SQLI_SUBQUERY_015": "<SUBQUERY_TEST_1>",
    "SQLI_LIKE_016": "<LIKE_TEST_1>",
    "SQLI_LIMIT_017": "<LIMIT_TEST_1>",
    "SQLI_REGEXP_018": "<REGEXP_TEST_1>",
    "SQLI_JSON_019": "<JSON_TEST_1>",
    "SQLI_CUSTOM_020": "<CUSTOM_SQLI_TEST_1>",
}
# registry.py
# -----------------------------------------
# SAFE / BENIGN TEST PAYLOADS FOR LAB USE
# -----------------------------------------

PAYLOAD_REGISTRY = {

    # -------------------------
    # XSS TEST PAYLOADS (SAFE)
    # -------------------------
    "XSS_REFLECTED_001": "<TEST_REFLECTED_XSS>",
    "XSS_IMG_ONERROR_002": "<TEST_IMG_ONERROR>",
    "XSS_SVG_003": "<TEST_SVG_PAYLOAD>",
    "XSS_IFRAME_004": "<TEST_IFRAME_PAYLOAD>",
    "XSS_EVENT_005": "<TEST_EVENT_HANDLER>",
    "XSS_INPUT_006": "<TEST_INPUT_FIELD>",
    "XSS_META_007": "<TEST_META_TAG>",
    "XSS_ONLOAD_008": "<TEST_ONLOAD_HANDLER>",
    "XSS_STYLE_009": "<TEST_STYLE_INJECTION>",
    "XSS_IMG_SRC_010": "<TEST_IMG_SRC>",
    "XSS_LINK_011": "<TEST_LINK_HREF>",
    "XSS_ONMOUSE_012": "<TEST_ONMOUSE_HANDLER>",
    "XSS_SCRIPT_SRC_013": "<TEST_SCRIPT_SRC>",
    "XSS_TEMPLATE_014": "<TEST_TEMPLATE_ELM>",
    "XSS_CUSTOM_015": "<TEST_CUSTOM_XSS>",


    # -------------------------
    # SQLi TEST PAYLOADS (SAFE)
    # -------------------------
    "SQLI_UNION_001": "<TEST_UNION_INJECTION>",
    "SQLI_BOOLEAN_002": "<TEST_BOOLEAN_BASED>",
    "SQLI_TIME_003": "<TEST_TIME_DELAY>",
    "SQLI_ERROR_004": "<TEST_ERROR_BASED>",
    "SQLI_STACKED_005": "<TEST_STACKED_QUERY>",
    "SQLI_BLIND_006": "<TEST_BLIND_SQLI>",
    "SQLI_UNION_SELECT_007": "<TEST_UNION_SELECT>",
    "SQLI_COMMENT_TRUNC_008": "<TEST_COMMENT_TRUNCATION>",
    "SQLI_CLEANSING_009": "<TEST_INPUT_CLEANSE>",
    "SQLI_AUTHBYPASS_010": "<TEST_AUTH_BYPASS>",
    "SQLI_CONCAT_011": "<TEST_CONCAT_FUNC>",
    "SQLI_HEX_012": "<TEST_HEX_ENCODED>",
    "SQLI_CAST_013": "<TEST_CAST_FUNC>",
    "SQLI_SLEEP_014": "<TEST_SLEEP_FUNC>",
    "SQLI_SUBQUERY_015": "<TEST_SUBQUERY_EXEC>",
    "SQLI_LIKE_016": "<TEST_LIKE_PATTERN>",
    "SQLI_LIMIT_017": "<TEST_LIMIT_CLAUSE>",
    "SQLI_REGEXP_018": "<TEST_REGEXP_PAYLOAD>",
    "SQLI_JSON_019": "<TEST_JSON_FUNC>",
    "SQLI_CUSTOM_020": "<TEST_CUSTOM_SQLI>",
}
